name: FactionScoreboard
main: com.ngxdev.faction.scoreboard.FS
version: 3.0
author: [Luke Kander]
softdepend: [Factions,PlaceholderAPI,MVdWPlaceholderAPI,LegacyFactions]
commands:
  factionscoreboard:
    aliases: [fs,map]

